### ISSUE TITLE
Not working with next js 13.x

### ISSUE THREAD

**Issue by arsal-786** [ankit1329/Eml-Parser#18]
error node_modules/eml-parser/index.js (23:17) @ EmlParser
- error Error [ReferenceError]: EmlParser is not defined
    at eval (webpack-internal:///(rsc)/./node_modules/eml-parser/index.js:17:28)
    at (rsc)/./node_modules/eml-parser/index.js (/home/arsl/WebstormProjects/visualprooffrontend/.next/server/app/api/uploadSingleEmail/route.js:6702:1)
    at __webpack_require__ (/home/arsl/WebstormProjects/visualprooffrontend/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./app/api/uploadSingleEmail/route.js:8:68)
    at (rsc)/./app/api/uploadSingleEmail/route.js (/home/arsl/WebstormProjects/visualprooffrontend/.next/server/app/api/uploadSingleEmail/route.js:440:1)
    at __webpack_require__ (/home/arsl/WebstormProjects/visualprooffrontend/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/next/dist/build/webpack/loaders/next-app-loader.js?name=app%2Fapi%2FuploadSingleEmail%2Froute&page=%2Fapi%2FuploadSingleEmail%2Froute&appPaths=&pagePath=private-next-app-dir%2Fapi%2FuploadSingleEmail%2Froute.js&appDir=%2Fhome%2Farsl%2FWebstormProjects%2Fvisualprooffrontend%2Fapp&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&rootDir=%2Fhome%2Farsl%2FWebstormProjects%2Fvisualprooffrontend&isDev=true&tsconfigPath=tsconfig.json&basePath=&assetPrefix=&nextConfigOutput=&preferredRegion=&middlewareConfig=e30%3D!:16:140)
    at (rsc)/./node_modules/next/dist/build/webpack/loaders/next-app-loader.js?name=app%2Fapi%2FuploadSingleEmail%2Froute&page=%2Fapi%2FuploadSingleEmail%2Froute&appPaths=&pagePath=private-next-app-dir%2Fapi%2FuploadSingleEmail%2Froute.js&appDir=%2Fhome%2Farsl%2FWebstormProjects%2Fvisualprooffrontend%2Fapp&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&rootDir=%2Fhome%2Farsl%2FWebstormProjects%2Fvisualprooffrontend&isDev=true&tsconfigPath=tsconfig.json&basePath=&assetPrefix=&nextConfigOutput=&preferredRegion=&middlewareConfig=e30%3D! (/home/arsl/WebstormProjects/visualprooffrontend/.next/server/app/api/uploadSingleEmail/route.js:429:1)
    at __webpack_require__ (/home/arsl/WebstormProjects/visualprooffrontend/.next/server/webpack-runtime.js:33:43)
    at __webpack_exec__ (/home/arsl/WebstormProjects/visualprooffrontend/.next/server/app/api/uploadSingleEmail/route.js:20356:39)
    at /home/arsl/WebstormProjects/visualprooffrontend/.next/server/app/api/uploadSingleEmail/route.js:20357:28
    at Object.<anonymous> (/home/arsl/WebstormProjects/visualprooffrontend/.next/server/app/api/uploadSingleEmail/route.js:20360:3)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at requirePage (/home/arsl/WebstormProjects/visualprooffrontend/node_modules/next/dist/server/require.js:112:75)
    at /home/arsl/WebstormProjects/visualprooffrontend/node_modules/next/dist/server/load-components.js:80:84
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async loadComponentsImpl (/home/arsl/WebstormProjects/visualprooffrontend/node_modules/next/dist/server/load-components.js:80:26)
    at async DevServer.findPageComponentsImpl (/home/arsl/WebstormProjects/visualprooffrontend/node_modules/next/dist/server/next-server.js:439:36) {
  digest: undefined
}

**Comment by Nuf1i** [comment]
Any update ?

**Comment by ankit1329** [comment]
@Nuf1i @arsal-786 Please share some example code which is not working for this
